"""
Alembic script template — generates clean migration files.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41ae4f6d28ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_file', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AUDITOR', 'VIEWER', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('sensitive_cols', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('target_col', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_table('governance_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('metric', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_rules_id'), 'governance_rules', ['id'], unique=False)
    op.create_index(op.f('ix_governance_rules_model_id'), 'governance_rules', ['model_id'], unique=False)
    op.create_table('audit_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'PASSED', 'FLAGGED', 'BLOCKED', name='audit_status_enum'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('demographic_parity', sa.Float(), nullable=True),
    sa.Column('equalized_odds_tpr', sa.Float(), nullable=True),
    sa.Column('equalized_odds_fpr', sa.Float(), nullable=True),
    sa.Column('disparate_impact', sa.Float(), nullable=True),
    sa.Column('overall_auroc', sa.Float(), nullable=True),
    sa.Column('overall_accuracy', sa.Float(), nullable=True),
    sa.Column('subgroup_divergence', sa.Float(), nullable=True),
    sa.Column('audit_report_path', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_dataset_id'), 'audit_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_audit_runs_id'), 'audit_runs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_runs_model_id'), 'audit_runs', ['model_id'], unique=False)
    op.create_index(op.f('ix_audit_runs_status'), 'audit_runs', ['status'], unique=False)
    op.create_table('bias_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('bias_type', sa.String(length=100), nullable=False),
    sa.Column('affected_group', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mitigation_applied', sa.Boolean(), nullable=False),
    sa.Column('mitigation_type', sa.String(length=100), nullable=True),
    sa.Column('before_value', sa.Float(), nullable=True),
    sa.Column('after_value', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bias_flags_audit_id'), 'bias_flags', ['audit_id'], unique=False)
    op.create_index(op.f('ix_bias_flags_id'), 'bias_flags', ['id'], unique=False)
    op.create_table('ethics_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_runs.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['governance_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ethics_checks_audit_id'), 'ethics_checks', ['audit_id'], unique=False)
    op.create_index(op.f('ix_ethics_checks_id'), 'ethics_checks', ['id'], unique=False)
    op.create_index(op.f('ix_ethics_checks_rule_id'), 'ethics_checks', ['rule_id'], unique=False)
    op.create_table('explainability_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('feature_scores', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('prediction_id', sa.String(length=100), nullable=True),
    sa.Column('fidelity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explainability_results_audit_id'), 'explainability_results', ['audit_id'], unique=False)
    op.create_index(op.f('ix_explainability_results_id'), 'explainability_results', ['id'], unique=False)
    op.create_table('model_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('intended_use', sa.Text(), nullable=True),
    sa.Column('out_of_scope_use', sa.Text(), nullable=True),
    sa.Column('training_data_desc', sa.Text(), nullable=True),
    sa.Column('evaluation_data', sa.Text(), nullable=True),
    sa.Column('performance_summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('fairness_summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_cards_audit_id'), 'model_cards', ['audit_id'], unique=True)
    op.create_index(op.f('ix_model_cards_id'), 'model_cards', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_cards_id'), table_name='model_cards')
    op.drop_index(op.f('ix_model_cards_audit_id'), table_name='model_cards')
    op.drop_table('model_cards')
    op.drop_index(op.f('ix_explainability_results_id'), table_name='explainability_results')
    op.drop_index(op.f('ix_explainability_results_audit_id'), table_name='explainability_results')
    op.drop_table('explainability_results')
    op.drop_index(op.f('ix_ethics_checks_rule_id'), table_name='ethics_checks')
    op.drop_index(op.f('ix_ethics_checks_id'), table_name='ethics_checks')
    op.drop_index(op.f('ix_ethics_checks_audit_id'), table_name='ethics_checks')
    op.drop_table('ethics_checks')
    op.drop_index(op.f('ix_bias_flags_id'), table_name='bias_flags')
    op.drop_index(op.f('ix_bias_flags_audit_id'), table_name='bias_flags')
    op.drop_table('bias_flags')
    op.drop_index(op.f('ix_audit_runs_status'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_model_id'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_id'), table_name='audit_runs')
    op.drop_index(op.f('ix_audit_runs_dataset_id'), table_name='audit_runs')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_governance_rules_model_id'), table_name='governance_rules')
    op.drop_index(op.f('ix_governance_rules_id'), table_name='governance_rules')
    op.drop_table('governance_rules')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
